### ISSUE TITLE
Errors during installation

### ISSUE THREAD

**Issue by majkinetor** [sanusart/gists-backup#6]
After  #5, this started happening during installation

```
C:\Users\*****\AppData\Roaming\npm\node_modules\gist-backup\node_modules\sync-prompt>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Python34\python.EXE" is v3.4.0, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:406:14)
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:193:7)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:90:13)
gyp ERR! stack     at Socket.emit (events.js:182:7)
gyp ERR! stack     at Pipe._onclose (net.js:475:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Korisnik\AppData\Roaming\npm\node_modules\gist-backup\node_modules\sync-prompt
gyp ERR! node -v v5.7.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
- ansi-regex@0.2.1 node_modules\gist-backup\node_modules\ansi-regex
- ansi-styles@1.1.0 node_modules\gist-backup\node_modules\ansi-styles
- escape-string-regexp@1.0.5 node_modules\gist-backup\node_modules\escape-string-regexp
- has-ansi@0.1.0 node_modules\gist-backup\node_modules\has-ansi
- lodash@4.6.1 node_modules\gist-backup\node_modules\lodash
- readline-sync@0.4.10 node_modules\gist-backup\node_modules\readline-sync
- strip-ansi@0.3.0 node_modules\gist-backup\node_modules\strip-ansi
- supports-color@0.2.0 node_modules\gist-backup\node_modules\supports-color
- chalk@0.5.1 node_modules\gist-backup\node_modules\chalk
- synchro-prompt@1.1.0 node_modules\gist-backup\node_modules\synchro-prompt
C:\Users\Korisnik\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gist-backup" "--global"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! sync-prompt@0.4.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sync-prompt@0.4.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sync-prompt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sync-prompt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sync-prompt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\*****\npm-debug.log
```

This is related to `node-gyp` which doesn't support python 3. This didn't happen before. Is that dependency is really necessary?

**Comment by sanusart** [comment]
Switched to different prompt package.
