### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by grantorin** [sanusart/gists-backup#8]
![screenshot_6](https://cloud.githubusercontent.com/assets/11960014/21497846/5882c8d6-cc30-11e6-8db8-2ca8eea53028.png)

**Comment by sanusart** [comment]
What nodejs version?
Was there any issues/errors during the installation?

**Comment by kingmaiku** [comment]
I had this too. I did notice that it never asked me the source github site. In my case, I am trying backup/save my notes off of an enterprise github server that is migrating.
I've attached all the details in a txt file.
Thanks!
[gist-backup.txt](https://github.com/sanusart/gists-backup/files/733118/gist-backup.txt)

**Comment by sanusart** [comment]
Hmm. It does not support using different URL. 
I don't have a enterprise account to test on, will you be willing to test it @kingmaiku ?

**Comment by kingmaiku** [comment]
yeah I'll give it a shot

**Comment by sanusart** [comment]
@kingmaiku Works as expected?

**Comment by kingmaiku** [comment]
hi @sanusart,
I just tried this and was not able to get very far.
here is the output I get.
```
/usr/lib/node_modules/gist-backup/gist-backup.js:23
        headers: {
        ^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by sanusart** [comment]
@kingmaiku Yep missing coma. Should be OK now.

**Comment by kingmaiku** [comment]
It looks like the original bug is still there.
The first part is working again.
```
gist-backup
Your GitHub Username? **********
Your GitHub Password? **********
Base URL if enterprise (Press Enter to use GitHub "https://api.github.com" by default)? https://**********
Path to back-up dir (will create if not exists)? gists
```
but then,
```
/usr/lib/node_modules/gist-backup/gist-backup.js:34
        data.forEach(function (gist) {
             ^

TypeError: data.forEach is not a function
    at Request.<anonymous> (/usr/lib/node_modules/gist-backup/gist-backup.js:34:14)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request._fireSuccess (/usr/lib/node_modules/gist-backup/node_modules/restler/lib/restler.js:226:10)
    at /usr/lib/node_modules/gist-backup/node_modules/restler/lib/restler.js:158:20
    at IncomingMessage.json (/usr/lib/node_modules/gist-backup/node_modules/restler/lib/restler.js:407:9)
    at IncomingMessage.auto (/usr/lib/node_modules/gist-backup/node_modules/restler/lib/restler.js:392:21)
    at Request._encode (/usr/lib/node_modules/gist-backup/node_modules/restler/lib/restler.js:195:29)
    at /usr/lib/node_modules/gist-backup/node_modules/restler/lib/restler.js:154:16
    at Request._decode (/usr/lib/node_modules/gist-backup/node_modules/restler/lib/restler.js:170:7)
```

**Comment by kingmaiku** [comment]
Hi @sanusart I just realized I didn't reference your username in my last post. I don't know if that means you didn't get notified, since the issue was closed.
